### ISSUE TITLE
Chưa xử lý được upload file 

### ISSUE THREAD

**Issue by LEANH1299HG** [ThanhNMSE130286/SEP490-G39-SU23#76]
Chưa tìm ra được server để upload file và sinh ra link

**Comment by ThanhNMSE130286** [comment]
Đã test và impliment upload file qua Firebase storage. Function upload trên js cần là async function, url thì gọi await uploadFileToFirebaseAndGetURL(file) bên trong firebase.js
Nếu còn thác mắc xem viedo trong drive hoặc liên hệ trưởng nhóm.
